name: navigation
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.1"

dependencies:
  auto_route: ^7.8.4
  flutter:
    sdk: flutter

  auth:
    path: ../feature/auth
  transactions:
    path: ../feature/transactions
  diagram:
    path: ../feature/diagram


dev_dependencies:
  flutter_lints: ^3.0.1
  dart_code_metrics: ^5.7.6
  auto_route_generator: ^7.3.2
  build_runner: 2.3.3