name: core
version: 0.0.1
publish_to: none
description: Project core module

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  data:
    path: ../data
  domain:
    path: ../domain
  navigation:
    path: ../navigation

  get_it: ^7.6.4
  dio: ^5.3.3
  logger: ^2.0.2+1
  easy_localization: ^3.0.3
  flutter_bloc: ^8.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  assets:
    - resources/langs/