name: auth
description: Home feature
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.1.1 <4.1.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../../core
  domain:
    path: ../../domain
  core_ui:
    path: ../../core_ui
  navigation:
    path: ../../navigation
  transactions:
    path: ../../feature/transactions
  equatable: ^2.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.6


flutter:
